package com.triara.jarperreport.constants;

public enum CmdChoices {
    GENERATE_JASPER_REPORT,
    GENERATE_JASPER_REPORT_WITH_PARAMETERS,
    GET_JASPER_REPORT_LIST_PARAMETERS,
    UNKNOWN_CHOICE,
    VERIFY_DB_CONNECTION
}